### ISSUE TITLE
Thaumcraft portals not being staged

### ISSUE THREAD

**Issue by happybandit360** [Darkhax-Minecraft/MobStages#10]
Thaumcraft portals register as entities as "thaumcraft:cultistportallesser" and "thaumcraft:cultistportalgreater". I have them staged via the
`mods.MobStages.addStage("thaumcraft", "thaumcraft:cultistportalgreater");`
method, but they are still spawning and allowing Cultists to spawn despite the stage being lock. Any suggestion on what to do about this?

**Comment by Darkhax** [comment]
This mod only stages the spawning of mobs. If it does not work with Thaumcraft's entities then it is likely that Thaumcraft does not spawn their mobs properly and are not using the right forge events. This would need to be fixed on their end.

**Comment by happybandit360** [comment]
I thought that might be the case. Thanks for your time.
