### ISSUE TITLE
[Question] Can we toggle an entire mod? 

### ISSUE THREAD

**Issue by Winddbourne** [Darkhax-Minecraft/MobStages#11]
I don't see a way to enable or disable mobs from an entire mod all at once . . . or to simply blanket allow all mobs to be spawned from spawners.  

I'm making  this a question rather than a feature request since I know most other Gamestage add ons can use blanket functions like this and I half expect it just got missed when the examples were being shown.  :)

**Comment by Darkhax** [comment]
No, a blanket function does not currently exist for this mod. You can potentially use CrT's built in registry to loop through all mobs from a mod though. That would be a good question for the CrT documentation or Discord, not sure what the syntax and specific code would be for this. 

As for official support, maybe. I would like to start focusing on 1.14.4 and not adding features to the older versions.

**Comment by Winddbourne** [comment]
Thanks for the reply. I'll make things work, it'll just be a bit of extra coding: Grimoire of Gaia has something like thirty mobs in it. 

I can't say I understand why anyone would do anything for 1.14+ though. Mojang has already announced that the thing is so buggy that the next edition has to be the "Bugs and Bees update" where they focus an entire version mostly on just balancing things and fixing bugs.  I'm leery of vanilla 1.14.4 let alone adding any mods to it. 

I want the water mechanics as much as anyone else . . . but that just leaves me wishing for either a 1.13 forge release or wanting to wait for 1.16 so I can get cave biomes. lol
