### ISSUE TITLE
can a mob with a nbt tag be spawned?

### ISSUE THREAD

**Issue by TRLWeiss** [Darkhax-Minecraft/MobStages#14]
I have no idea if this mod can support a mob with a complex nbt tag.When i execute the command 
/summon spider ~ ~ ~ {Passengers:[{id:"minecraft:skeleton",HandItems:[{id:"minecraft:bow",Count:1b}]}]}
I can spawn a spider jockey,but i do not know what will happen if i want to execute this command in your mod.

so btw... Can you share us an example to use the nbt in MobStages?

**Comment by Darkhax** [comment]
MobStages has no NBT support. Commands will bypass the mod as well.
