### ISSUE TITLE
[1.12.2] I can't use it on a certain mob

### ISSUE THREAD

**Issue by Nitrouille** [Darkhax-Minecraft/MobStages#16]
Hello,

I coded that the Sun Spirit from Aether Legacy cannot spawn since we reach a certain stage
But when I launch the game, it says that this entity doesn't exist

I know I put the right ID because I can summon it with this ID, and I copy-pasted the line of code so I cannot be wrong through this

**Comment by Darkhax** [comment]
Hello, that log entry is generated when the ID is not present in the entity registry. This can only happen if you have typed the ID incorrectly or the mod in question has not properly registered their entities. I've reviewed the code responsible for this warning and it seems to be working as intended.
