### ISSUE TITLE
Villagers still spawn, even when staged.

### ISSUE THREAD

**Issue by ofseaandstars** [Darkhax-Minecraft/MobStages#3]
Villagers will still spawn, even when staged correctly.

Here is my staging code:
`mods.MobStages.addStage("nether_unlock", "minecraft:villager");`

Here is crafttweaker log saying it's staged correctly:
`[INITIALIZATION][CLIENT][INFO] Adding minecraft:villager to stage.nether_unlock`

Here is the print out in game saying I do not have the stage:
![image](https://user-images.githubusercontent.com/5949532/44264328-0c0f9f80-a21a-11e8-85ea-433299d056ff.png)

Here's a screenshot of a villager (taken just after the stage printout):
![image](https://user-images.githubusercontent.com/5949532/44264352-2cd7f500-a21a-11e8-9dc6-9368dc504171.png)

I was wondering if it was something to do with the villager professions. Regardless, they are being marked as stage, but still spawning.

**Versions:**
-
**Forge:** 14.23.4.2756
**Game Stages:** 2.0.98
**Mob Stages:** 2.0.8
**CraftTweaker:** 4.1.9

**Comment by Darkhax** [comment]
Villagers don't actually spawn, they are generated as part of the world generation. Villagers have no spawning conditions, and because of that you can not disable them from spawning.

**Comment by ofseaandstars** [comment]
Ah, I see. That's a shame, but I suppose there's not much I can do about that. Thank you for your quick response!
