### ISSUE TITLE
add.Replacement not working as intended?

### ISSUE THREAD

**Issue by Alessandro404** [Darkhax-Minecraft/MobStages#4]
Using the last version of mob stages, MobStages-1.12.2-2.0.8.
Trying to spawn giant rats from various oddities instead of zombies doesnt works as intended. It spawn an enormous quantity of replacement mobs.

The giant rat does not have a natural spawn enabled in this mod. Maybe is something realated to that?

here's the script 

mods.MobStages.addStage("monster_from_the_depths", "minecraft:zombie");
mods.MobStages.addRange("minecraft:zombie", 32);
mods.MobStages.addReplacement("minecraft:zombie", "varodd:rat_giant");

![immagine](https://user-images.githubusercontent.com/8747581/44957773-201ff600-aed6-11e8-9b15-ad0ba9c273b1.png)

**Comment by Darkhax** [comment]
Thanks for the report, I will look into it a bit more. I think this is due to the giant rat being part of a different mob cap, so if the zombie cap isn't filled and zombies can still spawn, it will always try to spawn a rat.
